apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bdkjq98i8-python 
  janus-idp.io/tekton: bdkjq98i8-python
  backstage.io/kubernetes-id: bdkjq98i8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bdkjq98i8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  